[workspace]
resolver = "3"
members = [
    "text_analyzer/rust",
    "morse_trainer",
    "copy_file/rust",
    "simple_logger/rust",
    "matrix_ops/rust",
    "matrix_ops/bench/rust",
    "mini_shell/rust",
    "tiny_http_server/rust",
    "cpp_rust_bindings/rust",
    "rust_hosted_cpp/rust",
    "rust_python_bindings/core",
    "rust_python_bindings/bindings",
]
