//! Rust bindings for the C++ `exprkit` library.
//!
//! The C++ lives in `../cpp` and is a plain Bazel `cc_library` that has never
//! heard of Rust. This crate reaches it in three hops:
//!
//! ```text
//!   exprkit::Evaluator::eval(..)     this file -- safe, owned, Result
//!         |
//!         v
//!   ffi::eval(Pin<&mut _>, &str)     the #[cxx::bridge] module below,
//!         |                          plus the C++ cxx-build generates from it
//!         v
//!   exprkit::bridge::eval(..)        src/shim.cpp -- rust::Str to string_view
//!         |
//!         v
//!   exprkit::Evaluator::eval(..)     ../cpp/exprkit.cpp -- plain C++
//! ```
//!
//! Everything above `ffi` is safe to call. Nothing in this crate uses `unsafe`
//! outside the bridge declaration itself, which is `unsafe extern "C++"`
//! because trusting a C++ signature is exactly the kind of promise the compiler
//! cannot check.

use std::fmt;

use cxx::UniquePtr;

/// The raw FFI surface, generated by cxx from these declarations.
///
/// This module is an implementation detail and is deliberately private: its
/// types are `Pin<&mut _>` and `cxx::Exception`, neither of which belongs in a
/// public API. The wrappers below are the API.
#[cxx::bridge(namespace = "exprkit::bridge")]
mod ffi {
    unsafe extern "C++" {
        include!("shim.hpp");

        /// An opaque C++ type: Rust knows its name and nothing else, so it can
        /// only ever be held behind a pointer or a reference. `#[namespace]`
        /// overrides the module-level one because `Evaluator` lives directly in
        /// `exprkit`, while the functions live in `exprkit::bridge`.
        #[namespace = "exprkit"]
        type Evaluator;

        /// Declaring the return type as `Result<T>` is what makes cxx generate
        /// the try/catch. Without it a thrown `ExprError` would unwind into
        /// Rust frames that are not prepared for it, and the process aborts.
        ///
        /// *Every* function here is `Result`, including the ones that cannot
        /// fail as arithmetic. `format_value` builds a `std::string`, `names`
        /// builds a vector, `new_evaluator` and `clear` insert into a map --
        /// all of which can throw `std::bad_alloc`, and a throw that reaches
        /// this boundary uncaught is an abort. Deciding case by case which C++
        /// can allocate is exactly the reasoning that rots the first time the
        /// library changes, so the rule here is uniform and needs no thought.
        fn evaluate(text: &str) -> Result<f64>;
        fn format_value(value: f64) -> Result<String>;

        fn new_evaluator() -> Result<UniquePtr<Evaluator>>;

        /// `Pin<&mut Evaluator>` is how cxx spells a `C++&` to a type that may
        /// not be moved. A plain `&mut` would let safe Rust `mem::swap` two
        /// C++ objects, which is unsound for any type whose address matters.
        fn eval(evaluator: Pin<&mut Evaluator>, text: &str) -> Result<f64>;
        fn has(evaluator: &Evaluator, name: &str) -> Result<bool>;
        fn get(evaluator: &Evaluator, name: &str) -> Result<f64>;
        fn set(evaluator: Pin<&mut Evaluator>, name: &str, value: f64) -> Result<()>;
        fn names(evaluator: &Evaluator) -> Result<Vec<String>>;
        fn clear(evaluator: Pin<&mut Evaluator>) -> Result<()>;
    }
}

/// An error reported by the C++ library.
///
/// Its message is the `what()` of the C++ `exprkit::ExprError` that was thrown,
/// so the two CLIs report failures identically.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExprError {
    message: String,
}

impl ExprError {
    /// The message text, without the `ExprError:` prefix `Display` would add.
    pub fn message(&self) -> &str {
        &self.message
    }
}

impl fmt::Display for ExprError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for ExprError {}

/// The conversion that turns a caught C++ exception into an ordinary Rust
/// error. `cxx::Exception` borrows nothing, but it is a foreign type, so
/// keeping it out of the public API means callers never depend on cxx.
impl From<cxx::Exception> for ExprError {
    fn from(err: cxx::Exception) -> Self {
        ExprError {
            message: err.what().to_string(),
        }
    }
}

/// Shorthand for the result type every fallible call here returns.
pub type Result<T> = std::result::Result<T, ExprError>;

/// Unwraps a bridge call whose only failure mode is allocation.
///
/// These operations have no arithmetic error to report, so widening their
/// public signatures to `Result` would put a branch in every caller for a case
/// that ends the process anyway. Panicking instead keeps the API honest, and
/// the exchange is still worth making: an uncaught C++ exception crossing
/// `extern "C"` is an abort, while a Rust panic is a defined, unwindable
/// outcome. The bridge declaration is what buys that, not this function.
fn expect_no_throw<T>(result: std::result::Result<T, cxx::Exception>) -> T {
    match result {
        Ok(value) => value,
        Err(err) => panic!("exprkit: C++ threw where it should not: {}", err.what()),
    }
}

/// Evaluates one expression in a scratch environment.
///
/// The constants `pi` and `e` are in scope; an assignment is accepted but
/// discarded. Use an [`Evaluator`] to keep variables between calls.
///
/// # Errors
///
/// Returns [`ExprError`] on a syntax error, an unknown name, division by zero,
/// or a result that is not finite.
///
/// # Examples
///
/// ```
/// assert_eq!(exprkit::evaluate("2 ^ 10").unwrap(), 1024.0);
/// assert_eq!(exprkit::evaluate("1 / 0").unwrap_err().to_string(), "division by zero");
/// ```
pub fn evaluate(text: &str) -> Result<f64> {
    ffi::evaluate(text).map_err(ExprError::from)
}

/// Renders a value the way the CLIs print it: the shortest representation that
/// round-trips.
///
/// This calls into C++ rather than using Rust's own float formatting. The two
/// happen to agree today, but "happen to agree" is not a guarantee -- routing
/// both CLIs through one function is.
///
/// # Examples
///
/// ```
/// assert_eq!(exprkit::format_value(1.0), "1");
/// assert_eq!(exprkit::format_value(0.1 + 0.2), "0.30000000000000004");
/// ```
pub fn format_value(value: f64) -> String {
    expect_no_throw(ffi::format_value(value))
}

/// A calculator with a persistent set of named variables.
///
/// Owns a C++ `exprkit::Evaluator` through a `unique_ptr`. Dropping this runs
/// the C++ destructor.
///
/// # Examples
///
/// ```
/// let mut evaluator = exprkit::Evaluator::new();
/// evaluator.eval("r = 3").unwrap();
/// assert_eq!(evaluator.eval("r ^ 2").unwrap(), 9.0);
/// ```
pub struct Evaluator {
    inner: UniquePtr<ffi::Evaluator>,
}

impl Evaluator {
    /// Creates an evaluator holding the constants `pi` and `e`.
    pub fn new() -> Self {
        Evaluator {
            inner: expect_no_throw(ffi::new_evaluator()),
        }
    }

    /// Evaluates `text` against this environment, updating it.
    ///
    /// See the grammar in `../cpp/exprkit.hpp`. Assignments (`x = 1 + 2`)
    /// persist until [`clear`](Self::clear).
    ///
    /// # Errors
    ///
    /// As [`evaluate`]. A failed call leaves the environment untouched.
    pub fn eval(&mut self, text: &str) -> Result<f64> {
        ffi::eval(self.inner.pin_mut(), text).map_err(ExprError::from)
    }

    /// Reports whether `name` is currently defined.
    pub fn has(&self, name: &str) -> bool {
        expect_no_throw(ffi::has(&self.inner, name))
    }

    /// Returns the value bound to `name`.
    ///
    /// # Errors
    ///
    /// Returns [`ExprError`] if `name` is not defined.
    pub fn get(&self, name: &str) -> Result<f64> {
        ffi::get(&self.inner, name).map_err(ExprError::from)
    }

    /// Binds `name` to `value`.
    ///
    /// # Errors
    ///
    /// Returns [`ExprError`] if `value` is not finite, so the environment can
    /// never hold a value that would poison later arithmetic.
    pub fn set(&mut self, name: &str, value: f64) -> Result<()> {
        ffi::set(self.inner.pin_mut(), name, value).map_err(ExprError::from)
    }

    /// Returns every defined name, sorted.
    pub fn names(&self) -> Vec<String> {
        expect_no_throw(ffi::names(&self.inner))
    }

    /// Forgets every variable and restores the `pi` and `e` constants.
    pub fn clear(&mut self) {
        expect_no_throw(ffi::clear(self.inner.pin_mut()));
    }
}

impl Default for Evaluator {
    fn default() -> Self {
        Self::new()
    }
}

/// The C++ object has no `operator<<`, so this reports the environment instead
/// of the address, which is the only part worth seeing in a test failure.
impl fmt::Debug for Evaluator {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Evaluator")
            .field("names", &self.names())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // These tests are about the *seam*, not the arithmetic. Precedence,
    // parsing, and the error taxonomy are covered once, in C++, by
    // //cpp_rust_bindings/cpp:test_exprkit. What is only testable from this
    // side is whether values, ownership, and exceptions survive the crossing --
    // so that is what these check.

    #[test]
    fn floats_cross_the_boundary_bit_for_bit() {
        // Not a re-test of the parser: the point is that an f64 arrives with
        // every bit intact rather than being rounded somewhere in the FFI. Each
        // expected value is the identical computation done in Rust, so a
        // mismatch means the boundary changed the number.
        assert_eq!(evaluate("0.1 + 0.2").unwrap(), 0.1 + 0.2);
        assert_eq!(evaluate("1e-300 * 1e-3").unwrap(), 1e-300 * 1e-3);
        assert_eq!(evaluate("2 ^ -1074").unwrap(), f64::from_bits(1)); // subnormal
    }

    #[test]
    fn arguments_carry_a_length_rather_than_a_terminator() {
        // rust::Str is a pointer/length pair, so an interior NUL reaches the
        // C++ tokenizer as data instead of ending the string early. Were it
        // passed as a C string, "1 + \0" would arrive as "1 + " and fail with
        // "unexpected end of input"; it does not, so the NUL got through.
        assert_eq!(
            evaluate("").unwrap_err().message(),
            "unexpected end of input"
        );
        assert!(
            evaluate("1 + \0")
                .unwrap_err()
                .message()
                .starts_with("unexpected character: '")
        );
    }

    #[test]
    fn a_message_is_truncated_at_an_interior_nul() {
        // The return path is not symmetric with the argument path. cxx builds
        // the Err from `what()`, which is a C string, so the message stops at
        // the first NUL -- here mid-quote, losing the closing one. Nothing to
        // fix in this crate; the lesson is not to put arbitrary bytes in an
        // exception message and expect them back.
        assert_eq!(
            evaluate("1 + \0").unwrap_err().message(),
            "unexpected character: '"
        );
    }

    #[test]
    fn a_non_utf8_message_is_converted_lossily() {
        // The C++ tokenizer works in bytes, so a multi-byte character makes it
        // quote a lone continuation byte -- text that is not valid UTF-8 and so
        // cannot be a Rust &str. cxx substitutes U+FFFD rather than failing,
        // which is worth knowing: an error message can arrive altered.
        assert_eq!(
            evaluate("1 + \u{2212}").unwrap_err().message(),
            "unexpected character: '\u{fffd}'"
        );
    }

    #[test]
    fn a_thrown_exception_arrives_as_an_err() {
        let err = evaluate("1 / 0").unwrap_err();
        assert_eq!(err.message(), "division by zero");
        assert_eq!(err.to_string(), "division by zero");
    }

    #[test]
    fn every_error_variant_survives_the_crossing() {
        // One per throw site in the C++, so a new failure mode cannot quietly
        // become an abort instead of an Err.
        for expression in [
            "",           // unexpected end of input
            "1 2",        // unexpected trailing input
            "1 $ 2",      // unexpected character
            "(1",         // expected ')'
            "nope",       // unknown name
            "nope(1)",    // unknown function
            "1 / 0",      // division by zero
            "1e308 * 10", // not finite
            "1e400",      // out of range
        ] {
            assert!(
                evaluate(expression).is_err(),
                "expected `{expression}` to fail"
            );
        }
    }

    #[test]
    fn the_error_type_is_a_std_error() {
        fn boxed(text: &str) -> std::result::Result<f64, Box<dyn std::error::Error>> {
            Ok(evaluate(text)?)
        }

        assert_eq!(boxed("6 * 7").unwrap(), 42.0);
        assert_eq!(boxed("1 / 0").unwrap_err().to_string(), "division by zero");
    }

    #[test]
    fn an_evaluator_owns_its_cpp_state_across_calls() {
        let mut evaluator = Evaluator::new();
        evaluator.eval("x = 2").unwrap();
        assert_eq!(evaluator.eval("x ^ 10").unwrap(), 1024.0);
        assert_eq!(evaluator.get("x").unwrap(), 2.0);
    }

    #[test]
    fn two_evaluators_do_not_share_state() {
        let mut first = Evaluator::new();
        let mut second = Evaluator::new();
        first.eval("x = 1").unwrap();
        assert!(first.has("x"));
        assert!(!second.has("x"));
        assert!(second.eval("x").is_err());
    }

    #[test]
    fn set_and_get_round_trip_through_cpp() {
        let mut evaluator = Evaluator::new();
        evaluator.set("k", -1.5).unwrap();
        assert!(evaluator.has("k"));
        assert_eq!(evaluator.get("k").unwrap(), -1.5);
        assert!(evaluator.set("bad", f64::NAN).is_err());
        assert!(!evaluator.has("bad"));
    }

    #[test]
    fn names_arrive_as_an_owned_vec_of_string() {
        let mut evaluator = Evaluator::new();
        assert_eq!(evaluator.names(), ["e", "pi"]);
        evaluator.set("zeta", 1.0).unwrap();
        evaluator.set("alpha", 2.0).unwrap();
        assert_eq!(evaluator.names(), ["alpha", "e", "pi", "zeta"]);

        // The Vec is Rust-owned: it outlives the C++ call that produced it and
        // is dropped by Rust's allocator, not C++'s.
        let names = evaluator.names();
        drop(evaluator);
        assert_eq!(names.len(), 4);
    }

    #[test]
    fn clear_resets_the_cpp_environment() {
        let mut evaluator = Evaluator::new();
        evaluator.set("x", 1.0).unwrap();
        evaluator.clear();
        assert!(!evaluator.has("x"));
        assert_eq!(evaluator.names(), ["e", "pi"]);
    }

    #[test]
    fn format_value_matches_the_cpp_cli() {
        assert_eq!(format_value(1.0), "1");
        assert_eq!(format_value(-0.5), "-0.5");
        assert_eq!(format_value(0.1 + 0.2), "0.30000000000000004");
        assert_eq!(format_value(1e21), "1e+21");
    }

    #[test]
    fn debug_shows_the_environment() {
        let evaluator = Evaluator::new();
        assert_eq!(
            format!("{evaluator:?}"),
            r#"Evaluator { names: ["e", "pi"] }"#
        );
    }
}
