//! Rust bindings for the C++ `lrukit` cache.
//!
//! The C++ lives in `../cpp`. Unlike the library in
//! `../../cpp_rust_bindings/cpp`, it has no build file, no test binary, and no
//! CLI of its own: this crate compiles it (`build.rs`), tests it
//! (`tests/cache.rs`), and is the only program that runs it (`src/main.rs`).
//! The C++ is still written as if none of that were true -- it includes no cxx
//! header and names no Rust type -- so the dependency points one way only.
//!
//! A call reaches the library in three hops:
//!
//! ```text
//!   lrukit::Cache::get(..)           this file -- safe, owned, Option/Result
//!         |
//!         v
//!   ffi::get(Pin<&mut _>, &str, ..)  the #[cxx::bridge] module below,
//!         |                          plus the C++ cxx-build generates from it
//!         v
//!   lrukit::bridge::get(..)          src/shim.cpp -- rust::Str to string_view
//!         |
//!         v
//!   lrukit::Cache::find(..)          ../cpp/lrukit.cpp -- plain C++
//! ```
//!
//! Everything above `ffi` is safe to call. Nothing in this crate uses `unsafe`
//! outside the bridge declaration itself, which is `unsafe extern "C++"`
//! because trusting a C++ signature is exactly the kind of promise the compiler
//! cannot check.

use std::fmt;

use cxx::UniquePtr;

/// The raw FFI surface, generated by cxx from these declarations.
///
/// This module is an implementation detail and is deliberately private except
/// for the shared struct re-exported below: its types are `Pin<&mut _>`,
/// `CxxString`, and `cxx::Exception`, none of which belongs in a public API.
/// The wrappers further down are the API.
#[cxx::bridge(namespace = "lrukit::bridge")]
mod ffi {
    /// A snapshot of a cache's counters.
    ///
    /// This is a cxx *shared* struct: cxx emits both the Rust definition and a
    /// C++ one, and the two are the same bytes, so `stats` returns it by value
    /// with no conversion at the boundary. That is the whole reason it is
    /// declared here rather than bound as an opaque type -- five plain integers
    /// do not need an accessor each.
    ///
    /// The library has its own `lrukit::Stats` of the same shape, and the shim
    /// copies field by field between them. Sharing this struct all the way down
    /// would mean `../cpp/lrukit.hpp` including a generated cxx header, which is
    /// the one thing that directory must not do.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    struct CacheStats {
        hits: u64,
        misses: u64,
        evictions: u64,
        size: usize,
        capacity: usize,
    }

    unsafe extern "C++" {
        include!("shim.hpp");

        /// An opaque C++ type: Rust knows its name and nothing else, so it can
        /// only ever be held behind a pointer or a reference. `#[namespace]`
        /// overrides the module-level one because `Cache` lives directly in
        /// `lrukit`, while the functions live in `lrukit::bridge`.
        #[namespace = "lrukit"]
        type Cache;

        /// Declaring the return type as `Result<T>` is what makes cxx generate
        /// the try/catch. Without it a thrown `CacheError` would unwind into
        /// Rust frames that are not prepared for it, and the process aborts.
        ///
        /// *Every* function here is `Result`, including the ones with no error
        /// of their own to report. `keys` builds a vector of strings, `stats`
        /// and `len` at least touch the object, and any of them can be reached
        /// while the allocator is out of memory -- `std::bad_alloc` is a throw
        /// like any other, and a throw that reaches this boundary uncaught is
        /// an abort. Deciding case by case which C++ can allocate is exactly
        /// the reasoning that rots the first time the library changes, so the
        /// rule here is uniform and needs no thought.
        fn new_cache(capacity: usize) -> Result<UniquePtr<Cache>>;

        /// `Pin<&mut Cache>` is how cxx spells a `C++&` to a type that may not
        /// be moved. A plain `&mut` would let safe Rust `mem::swap` two C++
        /// objects, which is unsound for any type whose address matters -- and
        /// `Cache` is such a type twice over, since its map holds iterators
        /// into its own list.
        fn put(cache: Pin<&mut Cache>, key: &str, value: &str) -> Result<bool>;

        /// The out-parameter form of `Cache::find`. C++ answers with a pointer
        /// that is null on a miss; handing Rust a raw pointer into the cache
        /// would export exactly the lifetime problem this layer exists to
        /// absorb, so the answer arrives split in two: `bool` for "was it
        /// there", `out` for the value. [`Cache::get`] puts it back together as
        /// an `Option<String>`.
        ///
        /// `Pin<&mut CxxString>` is a `std::string&`. The C++ writes to it only
        /// on a hit and leaves it untouched on a miss.
        fn get(cache: Pin<&mut Cache>, key: &str, out: Pin<&mut CxxString>) -> Result<bool>;

        /// Takes `&Cache`, not `Pin<&mut Cache>`, because looking a key up with
        /// `contains` deliberately does not reorder the cache. The signature is
        /// the guarantee: a `const` method here is a `&self` method in Rust.
        fn contains(cache: &Cache, key: &str) -> Result<bool>;
        fn erase(cache: Pin<&mut Cache>, key: &str) -> Result<bool>;
        fn clear(cache: Pin<&mut Cache>) -> Result<()>;
        fn keys(cache: &Cache) -> Result<Vec<String>>;
        fn len(cache: &Cache) -> Result<usize>;
        fn capacity(cache: &Cache) -> Result<usize>;
        fn stats(cache: &Cache) -> Result<CacheStats>;
        fn format_stats(stats: &CacheStats) -> Result<String>;
    }
}

pub use ffi::CacheStats;

/// An error reported by the C++ library.
///
/// Its message is the `what()` of the C++ `lrukit::CacheError` that was thrown.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CacheError {
    message: String,
}

impl CacheError {
    /// The message text.
    pub fn message(&self) -> &str {
        &self.message
    }
}

impl fmt::Display for CacheError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for CacheError {}

/// The conversion that turns a caught C++ exception into an ordinary Rust
/// error. `cxx::Exception` borrows nothing, but it is a foreign type, so
/// keeping it out of the public API means callers never depend on cxx.
impl From<cxx::Exception> for CacheError {
    fn from(err: cxx::Exception) -> Self {
        CacheError {
            message: err.what().to_string(),
        }
    }
}

/// Shorthand for the result type every fallible call here returns.
pub type Result<T> = std::result::Result<T, CacheError>;

/// Unwraps a bridge call whose only failure mode is allocation.
///
/// These operations have no error of their own to report, so widening their
/// public signatures to `Result` would put a branch in every caller for a case
/// that ends the process anyway. Panicking instead keeps the API honest, and
/// the exchange is still worth making: an uncaught C++ exception crossing
/// `extern "C"` is an abort, while a Rust panic is a defined, unwindable
/// outcome. The bridge declaration is what buys that, not this function.
fn expect_no_throw<T>(result: std::result::Result<T, cxx::Exception>) -> T {
    match result {
        Ok(value) => value,
        Err(err) => panic!("lrukit: C++ threw where it should not: {}", err.what()),
    }
}

impl fmt::Display for CacheStats {
    /// Formats the counters exactly as the C++ `lrukit::format_stats` does,
    /// by calling it. The wording of a stat line is library behavior, so there
    /// is one definition of it and this is not it.
    ///
    /// ```
    /// let cache = lrukit::Cache::new(4)?;
    /// assert_eq!(
    ///     cache.stats().to_string(),
    ///     "hits=0 misses=0 evictions=0 size=0/4 hit_rate=0.000",
    /// );
    /// # Ok::<(), lrukit::CacheError>(())
    /// ```
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&expect_no_throw(ffi::format_stats(self)))
    }
}

/// A fixed-capacity least-recently-used cache of strings.
///
/// Storing into a full cache evicts the least recently used entry. Reading with
/// [`get`](Cache::get) counts as a use; asking with [`contains`](Cache::contains)
/// does not.
///
/// ```
/// let mut cache = lrukit::Cache::new(2)?;
/// cache.put("a", "1")?;
/// cache.put("b", "2")?;
/// cache.get("a")?;            // "a" is now the most recently used
/// cache.put("c", "3")?;       // so "b" is what leaves
///
/// assert_eq!(cache.keys(), ["c", "a"]);
/// assert_eq!(cache.get("b")?, None);
/// # Ok::<(), lrukit::CacheError>(())
/// ```
pub struct Cache {
    inner: UniquePtr<ffi::Cache>,
}

impl Cache {
    /// Creates a cache holding at most `capacity` entries.
    ///
    /// Returns an error if `capacity` is zero: such a cache would evict
    /// everything on the way in, so it could only ever miss.
    ///
    /// ```
    /// assert!(lrukit::Cache::new(0).is_err());
    /// ```
    pub fn new(capacity: usize) -> Result<Self> {
        Ok(Cache {
            inner: ffi::new_cache(capacity)?,
        })
    }

    /// Stores `value` under `key` and marks it most recently used, evicting the
    /// least recently used entry if that overflows the cache.
    ///
    /// Returns `true` if `key` was not already present. Returns an error if
    /// `key` is empty.
    pub fn put(&mut self, key: &str, value: &str) -> Result<bool> {
        Ok(ffi::put(self.inner.pin_mut(), key, value)?)
    }

    /// Returns the value bound to `key`, marking it most recently used.
    ///
    /// Returns an error if `key` is empty; a key that is simply absent is
    /// `Ok(None)`, since a miss is the ordinary outcome a cache exists to have.
    ///
    /// ```
    /// let mut cache = lrukit::Cache::new(4)?;
    /// cache.put("k", "v")?;
    ///
    /// assert_eq!(cache.get("k")?, Some("v".to_string()));
    /// assert_eq!(cache.get("absent")?, None);
    /// assert!(cache.get("").is_err());
    /// # Ok::<(), lrukit::CacheError>(())
    /// ```
    pub fn get(&mut self, key: &str) -> Result<Option<String>> {
        // The C++ writes into this string on a hit. It is allocated per call
        // rather than kept as a field because a cached buffer would have to be
        // owned by `&mut self`, and handing out a `&str` borrowed from it would
        // pin the cache for as long as the caller held the value.
        cxx::let_cxx_string!(out = "");
        if !ffi::get(self.inner.pin_mut(), key, out.as_mut())? {
            return Ok(None);
        }
        // Every value in the cache arrived through `put`, which takes `&str`,
        // so this cannot fail. Asserting it rather than converting lossily is
        // what keeps that invariant a fact instead of a hope: if some future
        // path inserts bytes, this panics rather than silently substituting
        // replacement characters.
        let value = out
            .to_str()
            .expect("lrukit: a cache value was not UTF-8, but every value entered as a &str");
        Ok(Some(value.to_string()))
    }

    /// Reports whether `key` is present, without disturbing the cache and
    /// without counting a hit or a miss.
    ///
    /// Returns an error if `key` is empty.
    pub fn contains(&self, key: &str) -> Result<bool> {
        Ok(ffi::contains(&self.inner, key)?)
    }

    /// Removes `key`, returning whether it was present.
    ///
    /// Returns an error if `key` is empty.
    pub fn remove(&mut self, key: &str) -> Result<bool> {
        Ok(ffi::erase(self.inner.pin_mut(), key)?)
    }

    /// Drops every entry, keeping the counters.
    pub fn clear(&mut self) {
        expect_no_throw(ffi::clear(self.inner.pin_mut()));
    }

    /// Returns every key, most recently used first.
    ///
    /// The `Vec<String>` is owned by Rust and outlives the cache.
    pub fn keys(&self) -> Vec<String> {
        expect_no_throw(ffi::keys(&self.inner))
    }

    /// The number of entries currently held.
    pub fn len(&self) -> usize {
        expect_no_throw(ffi::len(&self.inner))
    }

    /// Whether the cache holds no entries.
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// The maximum number of entries this cache will hold.
    pub fn capacity(&self) -> usize {
        expect_no_throw(ffi::capacity(&self.inner))
    }

    /// A snapshot of the hit, miss, and eviction counters.
    ///
    /// ```
    /// let mut cache = lrukit::Cache::new(1)?;
    /// cache.put("a", "1")?;
    /// cache.get("a")?;
    /// cache.get("b")?;
    /// cache.put("c", "3")?;
    ///
    /// let stats = cache.stats();
    /// assert_eq!((stats.hits, stats.misses, stats.evictions), (1, 1, 1));
    /// # Ok::<(), lrukit::CacheError>(())
    /// ```
    pub fn stats(&self) -> CacheStats {
        expect_no_throw(ffi::stats(&self.inner))
    }
}

impl fmt::Debug for Cache {
    /// Hand-written because `UniquePtr<ffi::Cache>` is opaque and would print
    /// as an address. Deliberately shows the shape and not the contents: a
    /// `{:?}` on a cache holding a megabyte of values should not print it.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Cache")
            .field("len", &self.len())
            .field("capacity", &self.capacity())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // These tests cover the *seam*: what happens when a value, a miss, an
    // exception, or an owned buffer crosses between the languages. The cache's
    // own behavior -- eviction order, promotion, counters -- is covered in
    // tests/cache.rs. The split is by subject, not by language, because there
    // is only one language of tests here.

    fn cache_with(entries: &[(&str, &str)]) -> Cache {
        let mut cache = Cache::new(8).expect("capacity 8 is valid");
        for (key, value) in entries {
            cache.put(key, value).expect("keys in tests are non-empty");
        }
        cache
    }

    #[test]
    fn a_miss_leaves_the_out_parameter_untouched() {
        // Reaches past the safe wrapper on purpose: `get` allocates a fresh
        // string every call, so this contract is invisible from outside and
        // would rot unnoticed. The shim promises not to write on a miss.
        let mut cache = cache_with(&[]);
        cxx::let_cxx_string!(out = "sentinel");

        let found = ffi::get(cache.inner.pin_mut(), "absent", out.as_mut())
            .expect("a non-empty key does not throw");

        assert!(!found);
        assert_eq!(out.to_str().unwrap(), "sentinel");
    }

    #[test]
    fn a_hit_overwrites_whatever_the_out_parameter_held() {
        let mut cache = cache_with(&[("k", "v")]);
        cxx::let_cxx_string!(out = "sentinel");

        let found = ffi::get(cache.inner.pin_mut(), "k", out.as_mut())
            .expect("a non-empty key does not throw");

        assert!(found);
        assert_eq!(out.to_str().unwrap(), "v");
    }

    #[test]
    fn keys_and_values_may_contain_an_interior_nul() {
        // Arguments cross as rust::Str, a pointer/length pair, so a NUL is
        // data rather than a terminator. This is the asymmetry worth knowing:
        // exception messages cross as what(), a C string, and would truncate.
        // Nothing in ../cpp/lrukit.cpp puts caller data in a message, which is
        // why that hazard does not exist in this crate.
        let mut cache = cache_with(&[]);
        cache
            .put("a\0b", "x\0y")
            .expect("a NUL is not an empty key");

        assert_eq!(cache.get("a\0b").unwrap(), Some("x\0y".to_string()));
        assert_eq!(cache.get("a").unwrap(), None);
        assert_eq!(cache.keys(), ["a\0b"]);
    }

    #[test]
    fn a_value_may_be_empty_even_though_a_key_may_not() {
        let mut cache = cache_with(&[]);
        cache.put("k", "").expect("an empty value is fine");

        assert_eq!(cache.get("k").unwrap(), Some(String::new()));
        assert!(cache.contains("k").unwrap());
    }

    #[test]
    fn every_throw_site_arrives_as_an_err() {
        // The uniform `Result` rule in the bridge is only worth anything if
        // each throwing path is actually exercised. Adding a `throw` to the
        // C++ without adding a line here is how that erodes.
        let mut cache = cache_with(&[("k", "v")]);

        assert!(Cache::new(0).is_err(), "constructor");
        assert!(cache.put("", "v").is_err(), "put");
        assert!(cache.get("").is_err(), "get");
        assert!(cache.contains("").is_err(), "contains");
        assert!(cache.remove("").is_err(), "remove");
    }

    #[test]
    fn the_error_message_is_the_cpp_what_text() {
        let error = Cache::new(0).expect_err("zero capacity is rejected");

        assert_eq!(error.message(), "capacity must be at least 1");
        assert_eq!(error.to_string(), "capacity must be at least 1");
        assert_eq!(
            cache_with(&[]).put("", "v").unwrap_err().message(),
            "key must not be empty"
        );
    }

    #[test]
    fn a_cache_error_boxes_as_a_std_error() {
        let error: Box<dyn std::error::Error> = Box::new(Cache::new(0).unwrap_err());

        assert_eq!(error.to_string(), "capacity must be at least 1");
    }

    #[test]
    fn a_failed_call_changes_nothing() {
        let mut cache = cache_with(&[("k", "v")]);

        assert!(cache.put("", "ignored").is_err());

        assert_eq!(cache.len(), 1);
        assert_eq!(cache.keys(), ["k"]);
        assert_eq!(cache.stats().hits, 0);
        assert_eq!(cache.stats().misses, 0);
    }

    #[test]
    fn ownership_survives_being_moved() {
        // UniquePtr<Cache> is a pointer, so moving the Rust wrapper never moves
        // the C++ object -- which is the point, given that its map holds
        // iterators into its own list. A cache that only worked where it was
        // built would be a poor value type.
        let mut boxed = vec![cache_with(&[("k", "v")])];
        assert_eq!(boxed[0].get("k").unwrap(), Some("v".to_string()));

        let mut taken = boxed.pop().expect("one cache went in");
        assert_eq!(taken.get("k").unwrap(), Some("v".to_string()));
    }

    #[test]
    fn keys_outlive_the_cache_they_came_from() {
        let keys = {
            let cache = cache_with(&[("a", "1"), ("b", "2")]);
            cache.keys()
        };

        // The Vec<String> was allocated by Rust's allocator inside C++ and
        // handed over whole, so dropping the cache does not touch it.
        assert_eq!(keys, ["b", "a"]);
    }

    #[test]
    fn cache_stats_crosses_as_plain_fields() {
        let mut cache = Cache::new(2).unwrap();
        cache.put("a", "1").unwrap();
        cache.put("b", "2").unwrap();
        cache.get("a").unwrap();
        cache.get("zz").unwrap();
        cache.put("c", "3").unwrap();

        assert_eq!(
            cache.stats(),
            CacheStats {
                hits: 1,
                misses: 1,
                evictions: 1,
                size: 2,
                capacity: 2,
            }
        );
    }

    #[test]
    fn stats_display_is_the_cpp_formatter() {
        let mut cache = Cache::new(4).unwrap();
        cache.put("a", "1").unwrap();
        cache.get("a").unwrap();
        cache.get("b").unwrap();

        // Not a re-implementation of the format string: this asserts that the
        // Rust side prints what the C++ produced, which is why there is no
        // second formatter to keep in sync.
        let stats = cache.stats();
        let from_cpp = expect_no_throw(ffi::format_stats(&stats));

        assert_eq!(stats.to_string(), from_cpp);
        assert_eq!(
            from_cpp,
            "hits=1 misses=1 evictions=0 size=1/4 hit_rate=0.500"
        );
    }

    #[test]
    fn debug_shows_the_shape_and_not_the_contents() {
        let cache = cache_with(&[("secret", "hunter2")]);

        assert_eq!(format!("{cache:?}"), "Cache { len: 1, capacity: 8 }");
    }
}
