#include "shim.hpp"

#include <string>
#include <string_view>

namespace lrukit::bridge {
namespace {

// view - borrows a rust::Str as a std::string_view.
//
// rust::Str is a pointer/length pair over UTF-8 bytes, which is exactly what
// string_view wraps, so this copies nothing. The borrow is valid for the
// duration of the call: Rust guarantees the &str outlives it, and the library
// copies any key or value it decides to keep.
std::string_view view(rust::Str text) {
  return std::string_view(text.data(), text.size());
}

} // namespace

// Every call below qualifies the library function it forwards to. Unqualified
// name lookup inside `lrukit::bridge` finds the bridge overload first, and
// `format_stats(stats)` would quietly recurse until the stack ran out.

std::unique_ptr<Cache> new_cache(std::size_t capacity) {
  // cxx's UniquePtr<Cache> is std::unique_ptr<lrukit::Cache>, so ownership
  // moves to Rust with no wrapper object in between. The Rust side drops it by
  // calling ~Cache through a generated deleter.
  return std::make_unique<Cache>(capacity);
}

bool put(Cache &cache, rust::Str key, rust::Str value) {
  return cache.put(view(key), view(value));
}

bool get(Cache &cache, rust::Str key, std::string &out) {
  const std::string *found = cache.find(view(key));
  if (found == nullptr) {
    // Leave `out` exactly as it arrived. The bool is the whole answer on a
    // miss, and a caller that ignored it would rather see its own string than
    // a silently emptied one.
    return false;
  }
  // Copy while the pointer is still known good. It points into the cache and
  // the next mutation may free it, so nothing about it may outlive this call.
  out = *found;
  return true;
}

bool contains(const Cache &cache, rust::Str key) {
  return cache.contains(view(key));
}

bool erase(Cache &cache, rust::Str key) { return cache.erase(view(key)); }

void clear(Cache &cache) { cache.clear(); }

rust::Vec<rust::String> keys(const Cache &cache) {
  // rust::Vec is a real Rust Vec, allocated by Rust's allocator through a
  // generated hook. Building it here and returning it by value hands Rust an
  // owned Vec<String> with no second copy on the far side.
  rust::Vec<rust::String> out;
  for (const std::string &key : cache.keys()) {
    out.push_back(rust::String(key));
  }
  return out;
}

std::size_t len(const Cache &cache) { return cache.size(); }

std::size_t capacity(const Cache &cache) { return cache.capacity(); }

CacheStats stats(const Cache &cache) {
  // The two structs are field-for-field identical and still have to be copied:
  // lrukit::Stats belongs to the library, CacheStats is generated by cxx, and
  // the whole point of the split is that ../../cpp never includes a cxx header.
  // Naming every field here is also what makes adding one to the library a
  // compile error rather than a silently unreported number.
  const Stats source = cache.stats();
  return CacheStats{
      .hits = source.hits,
      .misses = source.misses,
      .evictions = source.evictions,
      .size = source.size,
      .capacity = source.capacity,
  };
}

rust::String format_stats(const CacheStats &stats) {
  const Stats target{
      .hits = stats.hits,
      .misses = stats.misses,
      .evictions = stats.evictions,
      .size = stats.size,
      .capacity = stats.capacity,
  };
  return rust::String(lrukit::format_stats(target));
}

} // namespace lrukit::bridge
