[package]
name = "crossword_tui"
version = "0.1.0"
edition = "2024"

[lib]
name = "crossword_tui"
path = "src/lib.rs"

[[bin]]
name = "crossword"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
crossword_core = { path = "../core" }
dirs = "6"
ratatui = "0.29"
